name: CICD pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/animeverse:${{ github.run_number }}

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/animeverse:${{ github.run_number }}
    - name: Run the Docker container
      run: docker run -d -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/animeverse:${{ github.run_number }}
  build_and_host:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Change this to the version of Node.js you're using for your project

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.SECRET_GITHUB_TOKEN }}
        publish_dir: ./  # Change this to the build output directory
