name: CICD pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/animeverse:${{ github.run_number }}

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/animeverse:${{ github.run_number }}
    - name: Run the Docker container
      run: docker run -d -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/animeverse:${{ github.run_number }}
  build_and_host:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Add your build steps here based on your app's build system
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build  # Replace this with the build command specific to your app

    # Deploy the built app to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: master
        folder: ./dist

